config/routes.rb
Rails.application.routes.draw do
  get 'mystorage/show'
  get 'all_posts/show'
  get 'user_tops/show'
  resources :replies
  resources :posts
  get 'welcome/index'
  devise_for :users
  
  root 'welcome#index'
  
  get 'reply_to_posts_list/show'
  
  post 'match', to: 'replies#match'
  
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imagestorage.rb
class Imagestorage < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :replies
  has_one_attached :photo
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :post
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :imagestorages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/all_posts_controller.rb
class AllPostsController < ApplicationController
  def show
    @posts = Post.all.order(id: "DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/mystorage_controller.rb
class MystorageController < ApplicationController
  def show
    @ist = Imagestorage.where(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, :photo)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]
  protect_from_forgery

  def match 
    replyID = params[:reply_id]
    rep = Reply.find(replyID)
    rep.update(matched: true)
    
    ist = Imagestorage.new(user_id: rep.post.user.id, url: url_for(rep.photo))
    ist.save
    
    ist2 = Imagestorage.new(user_id: rep.id_of_user, url: url_for(rep.post.photo))
    ist2.save
    
    rep.post.destroy
    
    redirect_to '/welcome/index'
  end

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reply_params
      params.require(:reply).permit(:id_of_user, :reply_string, :post_id, :photo)
    end
end

app/controllers/reply_to_posts_list_controller.rb
class ReplyToPostsListController < ApplicationController
  def show
    temp_post = Post.find(params[:post_id])
    if temp_post.present?
      @replies = temp_post.replies.all
    end
  end
end

app/controllers/user_tops_controller.rb
class UserTopsController < ApplicationController
  def show
    @posts = current_user.posts
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/all_posts_helper.rb
module AllPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mystorage_helper.rb
module MystorageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/user_tops_helper.rb
module UserTopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/all_posts/show.html.erb
<h1>AllPosts#show</h1>
<% for p in @posts %>
  <div class="postContainer">
    <h3><%= p.title %></h3>
    <p><%= p.description %></p>
    <% if p.user.id == current_user.id %>
      <p>*you can't reply to yourself</p>
    <% else %>
      <a href="/replies/new?id=<%= p.id %>">reply</a>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagetrade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <h2>Menu</h2>
      <ul>
        <li><a href="/all_posts/show">all posts</a></li>
        <li><a href="/user_tops/show">user_top</a></li>
        <li><a href="/posts/new">create post</a></li>
        <li><a href="/mystorage/show">show my storage</a></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/mystorage/show.html.erb
<h1>Mystorage#show</h1>
<% for im in @ist %>
  <p><%= image_tag im.url, height: 100 %></p>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  
  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field" style="display:none;">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/replies/_form.html.erb
<%= form_with(model: reply) do |form| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
        <% reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display:none;">
    <%= form.label :id_of_user %>
    <%= form.text_field :id_of_user, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :reply_string %>
    <%= form.text_field :reply_string %>
  </div>
  
  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field" style="display:none;">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, value: params[:id] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Reply from email</th>
      <th>Reply string</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.id_of_user %></td>
        <td><%= reply.reply_string %></td>
        <td><%= reply.post_id %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reply from email:</strong>
  <%= @reply.id_of_user %>
</p>

<p>
  <strong>Reply string:</strong>
  <%= @reply.reply_string %>
</p>

<p>
  <strong>Post:</strong>
  <%= @reply.post_id %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>

app/views/reply_to_posts_list/show.erb
<h1>ReplyToPosts#show</h1>
<% for r in @replies %>
  <div style="padding: 5px; margin: 5px; background-color: rgb(255, 255, 200);">
    <p>replied on <%= r.created_at %></p>
    <p><%= r.reply_string %></p>
    <form action="/match" method="post">
      <input type="text" name="reply_id" value="<%= r.id %>" style="display:none;">
      <input type="submit" value="match">
    </form>
  </div>
<% end %>

app/views/user_tops/show.html.erb
<h1>UserTops#show</h1>
<% for p in @posts %>
  <div style="margin: 5px; padding:5px; background-color:rgb(255, 255, 200);">
    <h3><%= p.title %></h3>
    <p><%= p.description %></p>
    <a href="/reply_to_posts_list/show?post_id=<%= p.id %>">show replies</a>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<% if user_signed_in? %>
  <p>You are <%= current_user.email %></p>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
<h2>Menu</h2>
<a href="/user_tops/show">user page</a>